### ISSUE TITLE
Wrong line and column reported

### ISSUE THREAD

**Issue by alexislefebvre** [travis-ci/travis-yaml#51]
I pasted this code in the _Or paste your .travis.yml_ field:

```
language: php

php:
  - 5.4
  - 5.5
  - 5.6
- hhvm
```

It showed this error:

> syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1

The error is supposed to be at the line 7, `- hhvm` is not properly indentated.

**Comment by BanzaiMan** [comment]
I believe this is the YAML specification. The "wrong" indentation on line 7 is telling the parser that the entire file represents an array, but it's not, because line 1, column 1 does not define a scalar in the array.

Try feeding this document to any YAML parser, e.g., http://yaml-online-parser.appspot.com/.

**Comment by alexislefebvre** [comment]
@BanzaiMan here is the result with the other parser:

    Output

    ERROR:

    while parsing a block mapping
      in "<unicode string>", line 1, column 1:
        language: php
        ^
    expected <block end>, but found '-'
      in "<unicode string>", line 7, column 1:
        - hhvm
        ^
